import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './input.css'
import Layout from './layout/layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Creativa UI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>

        {children}
        </Layout>
        
        </body>
    </html>
  )
}
